### ISSUE TITLE
Mineshafts generating despite being disabled in config

### ISSUE THREAD

**Issue by PitchBright** [EnviroMine/EnviroMine-1.7#134] opened 2015-05-03 11:47 UTC
I've added v111 of the mod to a pre-existing world, using configs where I had pre-set:

```
"World Generation" {
    # Generates massive abandoned mineshafts (size doesn't cause lag)
    B:"Enable New Abandoned Mineshafts"=false

    # Generates mineshafts in villages
    B:"Enable Village MineShafts"=false
    B:"Generate Gases"=false
}
```

And yet, I'm seeing this in the server console:

6:48:43 AM EDT CONSOLE: thread/INFO] [enviromine]: New mine at 2048,66,2816 with rotation 0 in dimension 0

When I go to the location… there is no mineshaft at y:66. But when I dig down to about y:15 I come across this: https://imgur.com/JCFrQvl

That's the extent of the whole mineshaft.

**Comment by Funwayguy** [comment] 2015-05-03 12:36
Weird... This might have something to do with a previous mineshaft issue I've had

**Comment by Grim-Ascensions** [comment] 2015-07-16 13:50
My testing team has reported this occurring in Enviromine 3.119 despite my assurances of the disabled config option. This forced me to visually confirm the server log entry and partial mine presence in the beta for my newest modpack when running on my server. Sorry, didn't take a screenshot.

Its not game breaking, just seen the thread and thought to offer an updated confirmation.

**Comment by Funwayguy** [comment] 2015-07-17 14:41
I know what the problem is however I plan on fixing it in the rewrite due to how deep in the generator code the issue resides. As you said, it isn't game-breaking so I'm not going to rush it to release now just to end up doing it again for the rewrite.

**Comment by Funwayguy** [comment] 2015-07-17 14:45
PS: As a side note, there are more errors than just this one in the generator such as rounding errors in negative coordinates. I basically have to rewrite the whole mineshaft generator from the ground up.

**Comment by PitchBright** [comment] 2015-08-12 14:14
I think it just became game-breaking. A newly generated chunk is trying to generate a mineshaft… and it's spamming the console with 

CONSOLE: thread/ERROR] [enviromine]: EnviroMine tried to recursively generate Mineshafts! Too many villages shafts?

It causes the server to time-out, and nobody can play. Even after restart, it goes straight to spamming the console, with a constant stream of that error message.

**Comment by PitchBright** [comment] 2015-08-12 15:40
Further testing on a back-up server shows that even with "generate-structures=false" set in the server.properties file… EM still tries to design and generate mineshafts.

**Comment by GenDeathrow** [comment] 2015-08-24 19:30
I think I have a fix for this.. in version 1.3.120... I am trying to get it finished tonight.. its sitting on our prerelease branch atm.. doing testing

**Comment by PitchBright** [comment] 2015-08-24 19:43
*happy dance*

**Comment by GenDeathrow** [comment] 2015-08-27 21:42
alright is in the new updated.. should be fixed.. closing issue for now

**Closed by GenDeathrow** 2015-08-27 21:42 UTC
Labels: bug, resolved

**Comment by PitchBright** [comment] 2015-08-27 21:44
I grabbed it an hour ago… will test this, and #155 tonight… and reply with confirmation.

**Comment by PitchBright** [comment] 2015-08-28 09:23
I can't quite confirm this fix yet. I'm now experiencing a different issue in that chunk, related to Just Another Spawner. It's almost like that chunk is trying to re-generate or something. Once I get some feedback from Crudedragos at JAS, I'll know how to tackle that one problem, then I can come back and  confirm this fix.

**Comment by PitchBright** [comment] 2015-09-17 15:57
The problem seems to be fixed in the latest update. So I'd say "confirmed fixed".

**Comment by GenDeathrow** [comment] 2015-09-17 17:11
Thank goodness!

**Comment by PsychoLynx** [comment] 2016-03-09 16:53
Hey! Dunno if this is the right place to post, but it would seem like toggling off "Enable New Abandoned Mineshafts" has no effect on my worlds, the mineshafts are ginormous! Perhaps related to this?

**Comment by PitchBright** [comment] 2016-03-09 21:16
What version of EM are you using?

**Comment by PsychoLynx** [comment] 2016-03-10 04:38
124 (Latest), also tried 119 but didn't make a difference.

**Comment by PitchBright** [comment] 2016-03-10 05:48
Weird. It does sound like the same thing… maybe the issue should be reopened.
